# Generated by Django 4.1.7 on 2023-05-13 15:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория формы',
                'verbose_name_plural': 'Категории форм',
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='ФИО')),
                ('full_text', models.TextField(verbose_name='Текст формы')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время отправки формы')),
                ('phoneNumber', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='email')),
                ('idcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.category', verbose_name='Категория формы')),
            ],
            options={
                'verbose_name': 'Форма Обратной Связи',
                'verbose_name_plural': 'Формы Обратной Связи',
            },
        ),
    ]
